### ISSUE TITLE
bit.ly

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#27]
bit.ly found in blacklist.txt
This is a non-malicious URL shortening service

However, was not found in domains.txt
What is the difference between the 2 files?

**Comment by mkb2091** [comment]
Blacklist.txt is where I stored domains I've personally blacklisted and domains I've added from dead sources.

Domains.txt is the generated output which means that is made from all the upstream blocklists combined with blacklist.txt, it has all the IP addresses replaced with domains that resolve to that IP address and the whitelist and other upstream whitelists have been applied.

**Comment by mkb2091** [comment]
Since blacklist.txt did contain many domains which turned out to be false positives, I've removed all domains that I haven't manually blacklisted from it. I've also moved the files to a new folder to make it clearer that it is only for internal use during generation of output, not to be used as a file to be added to PiHole
