### ISSUE TITLE
xvideos.com

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#40]
Hi, this domain is on your list... you don't seem to be censoring XHamster or PornHub, so I think this one mistakenly snuck onto your list.
Please remove, as it's not malicious, and AFAIK you aren't meaning to censor!
Thanks

**Comment by mkb2091** [comment]
You are correct, there is no intention of censoring. It was caused by https://raw.githubusercontent.com/k2jp/abp-japanese-filters/master/abpjf.txt which has the adblock rule ||xvideos.com^$third-party
The current adblock parser uses that rule to block the whole domain, since domain based adblock can't only block when it is a third party.
I've removed the list that caused the false positive, so it should be fixed on the next release

**Comment by p1r473** [comment]
Thank you sir!
