### ISSUE TITLE
Query adlists

### ISSUE THREAD

**Issue by p1r473** [mkb2091/blockconvert#5]
Hi,
Great tool. I love the idea of using DNS to remove dead domains and reduce my massive 2 billion domains down.
However I am hoping you can add functionality similar to in pihole, which allows you to search through all or your lists and see which list a false positive domain  is originating from.
I use this with lists that have too many false positives, I remove.

![](https://i.imgur.com/XS349jh.jpg)

![](https://i.imgur.com/tPfUDLd.jpg)

**Comment by p1r473** [comment]
https://i.imgur.com/tPfUDLd.jpg
https://i.imgur.com/XS349jh.jpg

**Comment by mkb2091** [comment]
That's actually a good idea, currently I just search the data folder(eg using grep: `grep ^analytics.google.com$ data -r` or using ripgrep: `rg ^analytics.google.com$ data`

The limitation of the current approach is that if one of the lists blocks all subdomains(eg for previous example *.google.com), or the list blocks an IP address which reverse dns/passive dns converted into the domain then it then it won't be found using regular expression search. Even if the domain is found, it will show folder(eg `data/https%3A%2F%2Fhblock.molinero.dev%2Fhosts/blacklist.txt`) instead of url(eg `https://hblock.molinero.dev/hosts`)

Thanks for the suggestion, Ill try and write a script to find where a domain is from
