### ISSUE TITLE
What happened to the Blocked IP address list?

### ISSUE THREAD

**Issue by Cade66** [mkb2091/blockconvert#85]
Hi,

The _Blocked IP address list_'s size dropped from 5MB+ to ~300KB. Roughly 5MB less!

**Comment by mkb2091** [comment]
Thanks so much for pointing that out. The domain list also massively dropped from ~20MB to 92KB. The problem was that the filterlists.csv file, which contains a list of external lists to import and process, got emptied when moving the repository between disks. This meant it only had some IP addresses I'd added. I've reverted the deletion of the filterlists.csv file and regenerating the output lists, hopefully the issue should be fixed once the script has finished

**Comment by mkb2091** [comment]
I've reverted the commit that broke it, as that's a quicker solution
