### ISSUE TITLE
c.footprint.net

### ISSUE THREAD

**Issue by crssi** [mkb2091/blockconvert#88]
Site `https://www.24ur.com/` is completely broken due to listing `c.footprint.net`.

Cheers

**Comment by mkb2091** [comment]
https://dns.google/query?name=c.footprint.net shows the DNS response as 

`{
  "Status": 0,
  "TC": false,
  "RD": true,
  "RA": true,
  "AD": false,
  "CD": false,
  "Question": [
    {
      "name": "c.footprint.net.",
      "type": 1
    }
  ],
  "Answer": [
    {
      "name": "c.footprint.net.",
      "type": 1,
      "TTL": 59,
      "data": "127.0.0.1"
    }
  ],
  "Comment": "Response from 8.253.90.155."
}`

so it's IP is 127.0.0.1, points to the local computer instead of an actual server, which is why it is blocked. It seems www.24ur.com has the CNAME sni.star.24ur.com.c.footprint.net which is blocked because whatever tool you are using also blocks subdomains.
